# Generated by Django 2.2.2 on 2019-08-02 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_auto_20190802_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='program_manager',
        ),
        migrations.AddField(
            model_name='team',
            name='program_manager',
            field=models.ManyToManyField(null=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
