# Generated by Django 2.2.2 on 2019-08-02 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_auto_20190802_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='program_manager',
        ),
        migrations.AddField(
            model_name='team',
            name='program_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
