# Generated by Django 2.2.2 on 2019-08-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190802_0633'),
        ('projects', '0003_auto_20190802_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(null=True, to='teams.Team'),
        ),
    ]
